### ISSUE TITLE
"IOError: not opened for reading" when attempting to use "delay_with_resque" configuration.

### ISSUE THREAD

**Issue by keiththomps** [bugsnag/bugsnag-ruby#210]
When attempting to use the `delay_with_resque` configuration option I'm receiving:

`IOError: not opened for reading`

This is occurring [here](https://github.com/bugsnag/bugsnag-ruby/blob/v2.8.1/lib/bugsnag/delay/resque.rb#L15) when the `configuration` argument (`args[2]`) is having `to_json` called on it.

I've create a [sample rails application](https://github.com/keiththomps/test_rescue_bugsnag) to easily reproduce this. Start the rails app, start redis/resque, and visit the root URL. This is a completely stock rails 4.20 application and I'm seeing the same behavior on rails 4.1.8.

**Comment by ConradIrwin** [comment]
Thanks for the exceptionally detailed error report, it makes tracking these things down so much easier :).

We recently added a concept of "delivery" mechanisms to the gem, so it's been on my plate to re-write the older delay_with_resque configuration option to be implemented in terms of those for a while.

If you wanted to take a stab at it, I'd appreciate it, otherwise I'll try to fix this soon.

**Comment by BlakeMesdag** [comment]
@keiththomps this happens when trying to serialize the logger, ran into this a couple weeks ago.

**Comment by snmaynard** [comment]
We're planning on deprecating the resque delay configuration as we now have the [thread_queue](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/delivery/thread_queue.rb) delivery mechanism. Is there any reason to keep the resque delivery mechanism around now we have that?

**Comment by BlakeMesdag** [comment]
We still use the resque delivery in our main application, I'll see if I can get someone to switch it to the thread queue.

**Comment by Cawllec** [comment]
Closing this as we haven't heard back, feel free to re-open if you've got more information.
