### ISSUE TITLE
Weird Error in Newrelic

### ISSUE THREAD

**Issue by sahin** [bugsnag/bugsnag-ruby#265]
80,700	67.46%Bugsnag::Rack#call		0.002  s
39,100	32.68% Application code (in Bugsnag::Rack#call)  41.617  s

Sometimes we are seeing 40 seconds Bugsnag::Rack, 

![ldiltqithps5yxpryjzottjmox5lnpttccdbkj04vkw](https://cloud.githubusercontent.com/assets/2508980/11910744/c590c4b4-a5b2-11e5-94b1-c5d684021bc8.png)

**Comment by kattrali** [comment]
Thanks for the report @sahin. I'll take a look. Are there a lot of errors being reported in Bugsnag when this occurs, or any other details which you can provide?

**Comment by snmaynard** [comment]
Closing due to lack of response. 

If this is still causing an issue I would recommend letting us know what version of the notifier you are running and reopening it. Where are your servers located and do you see a corresponding external services call to bugsnag that is slow? It would help us narrow down whether it was a slow network call or some cpu issue.
