### ISSUE TITLE
Events with a large stack trace are silently ignored

### ISSUE THREAD

**Issue by braddunbar** [bugsnag/bugsnag-ruby#294]
Using version 4.0.2, events with a large enough stack trace will be silently ignored by bugsnag-ruby. In particular, `Bugsnag::Helpers.trim_if_needed` will remove the entire event rather than truncating its contents.

The ignored events I've seen contained three exceptions with approximately 200 items in the `stacktrace` field.

**Comment by kattrali** [comment]
Thank you for the report, @braddunbar. I dig some investigating to determine the best way we can selectively drop parts of the payload and not have requests rejected due to size. The results are in #295. 

If you have the time, can you send a copy of an example stack trace with 200 or so lines to support@bugsnag.com? I'd like to gather data and determine if there are heuristics we can apply to which lines of a stacktrace are dropped on the client side in cases like this. In the meantime, it will perform a truncation of the end of the stack trace array.

**Comment by kattrali** [comment]
Resolved with the release of [4.1.0](https://github.com/bugsnag/bugsnag-ruby/blob/master/CHANGELOG.md#410-11-may-2016).

**Comment by braddunbar** [comment]
Sure thing! I've just sent the stacktrace to the email above. Let me know if you need anything else and thanks for the quick turnaround! 👍🏻
