### ISSUE TITLE
Provide a way to refer to reported error

### ISSUE THREAD

**Issue by bolshakov** [bugsnag/bugsnag-ruby#312]
I have a rails middleware which renders server errors and want to provide a way to refer to happened exception. So the application user faced with error can tell me "Internal server error happens with id 6864bc12" and I'll know how to find this error.

Is there way to get some error token or link?

**Comment by martin308** [comment]
Sorry @bolshakov, we don't have a way of providing that at the moment due to the way our backend processes errors.

Are you using the [user identification](https://docs.bugsnag.com/platforms/ruby/other/#identifying-users) features of the ruby notifier? If so you can always look up the user and see any errors that particular user has experienced

**Comment by bolshakov** [comment]
Thank you, It will work out, but I could not identify error by just user id (and this field is already used for original purpose). So I'm going to use `user name` field as error id for now.

Do you consider adding explicit ability to specify searchable error identifier? It is extremely useful :

**Comment by snmaynard** [comment]
We are adding some features into the dashboard in the future that will allow you to do this in a slightly better way, but as you have a work around and this is more a ticket about our dashboard than the ruby notifier directly I will close this one out.

Thanks for the feedback @bolshakov!
