### ISSUE TITLE
Bugsnag.notify(e) issues DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead.

### ISSUE THREAD

**Issue by skarger** [bugsnag/bugsnag-ruby#356]
To reproduce:

```
[6] pry(main)> begin
[6] pry(main)*   raise ActiveRecord::StatementInvalid.new("")
[6] pry(main)* rescue Exception => ex
[6] pry(main)*   Bugsnag.notify(ex)
[6] pry(main)* end
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead.
```

The code in the bugsnag gem where this comes up looks to be
https://github.com/bugsnag/bugsnag-ruby/blob/42552a894bb2f70fd48df8b6bc9d3e3da7ba11aa/lib/bugsnag/notification.rb#L96

If `ex.cause` is `nil` (or otherwise falsy) it will fall through. If it hits `ex.original_exception` section the deprecation warning happens. `original_exception` is a deprecated Rails method.
```
        if ex.respond_to?(:cause) && ex.cause
          ex = ex.cause
        elsif ex.respond_to?(:continued_exception) && ex.continued_exception
          ex = ex.continued_exception
        elsif ex.respond_to?(:original_exception) && ex.original_exception
          ex = ex.original_exception
        else
          ex = nil
        end
```

One potential fix is to only require `ex.respond_to?(:cause)` and not also `ex.cause` to be truthy, although I don't know the reasons behind all these predicates.

**Comment by kattrali** [comment]
Thanks for the report, @skarger. This is a tricky one, since it affects both Rails (and potentially other libraries) and Ruby 2.1+ behavior. 

For example, If you are running Rails 4 using Ruby 2.1+ and remove the requirement for `ex.cause` to be truthy, then when an error occurs, the exception that Rails assigned to `original_exception` would be lost. Calling `original_exception` could be guarded by Rails version, but the change can also affect other libraries using `original_exception` and would also lose information.

**Comment by Cawllec** [comment]
`:original_exception` has been removed in the latest version of rails, 5.1.  This should not longer be an issue, especially in light of the context provided by @kattrali above.
