### ISSUE TITLE
Bugsnag not percolating routing errors

### ISSUE THREAD

**Issue by brea9482** [bugsnag/bugsnag-ruby#529]
Hi there -

I can't seem to configure Bugsnag to report routing errors (`ActionController::RoutingError`). We're using Rails 5.0 and Bugsnag 6.8.0. It seem this support should come out of the box but for some reason it's not working. 

Our config/initializers/bugsnag is as follows:

```
JOB_RUNNER = 'Job Runner'.freeze

Bugsnag.configure do |config|
  config.api_key = ENV.fetch('BUGSNAG_API_KEY')
  config.notify_release_stages = [ 'production' ]
end

Bugsnag.before_notify_callbacks << lambda { |notification|
  notification.context = JOB_RUNNER
}
```

Does anyone have any thoughts?

**Comment by mworthley-salsify** [comment]
hhmm, my first thought was that `RoutingError` was in the default ignore class in bugsnag. But this was removed in version 5.0.0 https://github.com/bugsnag/bugsnag-ruby/pull/308

Get the shovel! We'll keep on diggin'

**Comment by Cawllec** [comment]
Hi @brea9482, are you getting reports from any other sort of errors?

**Comment by brea9482** [comment]
Yes, everything else is working as expected.

**Comment by brea9482** [comment]
ok - try this repo out - it should be reproducible 

https://github.com/salsify/bugsnag-routing-test

**Comment by Cawllec** [comment]
Hi @brea9482, in Rails we capture errors as they are raised through the Rack server.  If a request raises an error we capture and notify it.
In the case of this `ActionController::RoutingError`, it's not actually being raised through Rack, it's instead responding with the error page and not raising an error, presumably to keep the application running as it hasn't entered a failure state (which 4** errors traditionally aren't).
If you explicitly raise a `RoutingError`, it will be caught and notified, but the example application won't due to the way Rails automatically handles them.

**Comment by brea9482** [comment]
got it - thanks for the explanation!

**Comment by MattyMc** [comment]
Hi @Cawllec, did you pursue capturing these errors through Bugsnag? If so, could you share how?

**Comment by xander-jones** [comment]
Hey @MattyMc, did you mean to @ @brea9482? We're not currently working on capturing these errors in Ruby.

**Comment by MattyMc** [comment]
Hi @Cawllec: Sorry for that, yes I did mean to tag @brea9482 to see if he came up with a solution for notifying Bugsnag on routing errors. I'm receiving an increasing number of those scary emails from Heroku: "Your failed requests threshold has passed 5%..." 😨 

I did find a simple solution though. At the bottom of my routes file I wildcard match any request, pick this up in a tiny ErrorsController where I throw the exception myself: 

`
#routes.rb
...
  match '*path' => 'errors#catch_404', via: :all
`

`
# errors_controller.rb
class ErrorsController < ApplicationController
  # Called on any request that doesn't have a matching route
  # Normally, ActionController will directly raise an error
  #   but this won't be captured at the application level.
  # So, we wildcard-match any route at the bottom of our
  #   routes file to this action and manually raise an
  #   ActionController::RoutingError with the path so that
  #   we can capture these requests and try to address them.
  def catch_404
    raise ActionController::RoutingError, request.path
  end
end
`

**Comment by brea9482** [comment]
hey @MattyMc -- yea I pretty much came up with the same solution as you
