### ISSUE TITLE
Ability to suppress default pii user information sent to bugsnag

### ISSUE THREAD

**Issue by ishields** [bugsnag/bugsnag-ruby#714]
### Description
Hello, I'd like to avoid sending email and first name to Bugsnag as this is PII and shouldn't be sent unless necessary (not sure why email and name would be needed for most cases).  I've tried overwriting the defaults by setting it on each controller action:
```
event.set_user(current_user.id, '', '')
```
however the pii is still sent.  Is there a way around sending this information or does this need to be built?  Thanks!

**Comment by mattdyoung** [comment]
Hi @ishields 

I can't see why your approach wouldn't work, assuming you're doing this in a callback in your controller as shown here:
https://docs.bugsnag.com/platforms/ruby/rails/customizing-error-reports/#updating-events-using-callbacks

It should also be possible to clear the user information in a global `add_on_error` callback, so that it's cleared for all errors:
https://docs.bugsnag.com/platforms/ruby/rails/customizing-error-reports/#on-error-callbacks

If this doesn't work could you confirm which version of bugsnag-ruby you're using? Also how is the user information such as the name and email address being set? Are you adding this when you configure Bugsnag or is it being determined automatically from your authentication framework?
https://docs.bugsnag.com/platforms/ruby/rails/#identifying-users

**Comment by mattdyoung** [comment]
Closing, but do let us know if the above guidance doesn't work for you. Thanks!

**Comment by xander-jones** [comment]
Hey @ishields, yeah with Devise `current_user` and the other user-related helpers will only be available in a controller or view scope (https://github.com/heartcombo/devise#controller-filters-and-helpers). It won't ever be available in an initializer as it runs prior to the application setting the user logged in, but as this is a callback it will be run in the context of the calling function, so should be available for views & controllers.

With regards to the data in a report by default: I hear you, this is a bit of a balancing act between what some people _do_ want include, and others _don't_. Because we add this data to reports by default, it's documented prominently in the index of the Rails documentation (https://docs.bugsnag.com/platforms/ruby/rails/#identifying-users). This hasn't fallen on deaf ears, but it's not a behaviour that we're looking to make changes to at the moment. 

Your masking callback seems reasonable to me to use the Bugsnag library in the way you want to. As a side note, if you're looking for a way to remove data from Bugsnag upon request of a user, we've got some example on how to automate this process here through our Data Access API: https://docs.bugsnag.com/api/data-access/gdpr-examples/

**Comment by ishields** [comment]
@xander-jones Thank you for your fast reply!

Makes sense about the current_user.  Since this doesn't work, you might consider updating this documentation accordingly where it specifically says to add this code to the initializer. https://docs.bugsnag.com/platforms/ruby/rails/customizing-error-reports/#on-error-callbacks

Great.  Just wanted to make sure it was considered and seems like you all are doing the right thing by flagging it in documentation.  And thanks for pointing me to that documentation.

**Comment by xander-jones** [comment]
Agreed, I'm on it! Thanks for your feedback 🙏
